trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - AzurePipelines/*

pool:
  vmImage: ubuntu-latest

variables:
  - group: BLOG_VARIABLES

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build Project
        steps:
          - task: Maven@3
            displayName: "Maven Clean"
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.21"
              jdkArchitectureOption: "x64"
              goals: "clean"
          - task: Maven@3
            displayName: "Maven Test"
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.21"
              jdkArchitectureOption: "x64"
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: "test"
          - task: Maven@3
            displayName: "Maven Package"
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              javaHomeOption: "JDKVersion"
              jdkVersionOption: "1.21"
              jdkArchitectureOption: "x64"
              goals: "-Dmaven.test.skip -Dspring.profiles.active=prod package"
          - task: CopyFiles@2
            displayName: "Copy Files"
            inputs:
              SourceFolder: "$(System.DefaultWorkingDirectory)"
              Contents: |
                **/target/*.?(war|jar)
                Dockerfile
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              artifact: BlogAppBuild
              publishLocation: 'pipeline'