version: '3.1'
services:
  blog-db:
    container_name: blog_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=blogdb
  blog-api:
    container_name: blog_api
    image: blog
    ports:
      - "8080:8080"
    depends_on:
      - db
  blog-vue:
    container_name: blog_vue
    image: blog-vue
    ports:
      - "8081:80"
    depends_on:
      - api
