spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:postgresql://az-llz-nova-blog-dev-en1-pgs01.postgres.database.azure.com:5432/blogdb"
    username: "psqladmin"
    password: "H@Sh1CoR3!"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

application:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "devzouftou@gmail.com"
    password: ${APPLICATION_MAIL:xxxxxx}