spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/blogdb}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true

application:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "devzouftou@gmail.com"
    password: ${APPLICATION_MAIL_PASSWORD:xxxxxx}
    systemName: Zouftou Blog
    systemEmail: system@zouftoublog.com
    adminName: Zouftou Admin
    adminEmail: admin@zouftoublog.com