spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:blogdb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  threads:
    virtual:
      enabled: true

application:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "devzouftou@gmail.com"
    password: ${APPLICATION_MAIL_PASSWORD:xxxxxx}
    systemName: Zouftou Blog
    systemEmail: system@zouftoublog.com
    adminName: Zouftou Admin
    adminEmail: admin@zouftoublog.com